# fly.toml app configuration file generated for bold-haze-5083 on 2023-09-06T09:16:02+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bold-haze-5083"
primary_region = "lhr"

[build]
  image = "flyio/hellofly:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
